### ISSUE TITLE
[org.apache.myfaces.application.ApplicationImpl] () Undefined component type net.bootsfaces.layout.***

### ISSUE THREAD

**Issue by rayidimurali** [twbs/bootstrap#18113]
Hey I am trying to setup bootsfaces in my JSF application, I am seeing below error, can someone please help?

[org.apache.myfaces.application.ApplicationImpl] () Undefined component type net.bootsfaces.layout.Row

at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1437)
	at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1405)
	at org.jboss.weld.integration.webtier.jsf.ForwardingApplication.createComponent(ForwardingApplication.java:122)
	at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.createComponent(ComponentTagHandlerDelegate.java:576)
	at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:284)
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:50)
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:46)
	at org.apache.myfaces.view.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:86)
	at org.apache.myfaces.view.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:178)
	at org.apache.myfaces.view.facelets.impl.TemplateContextImpl$TemplateManagerImpl.apply(TemplateContextImpl.java:193)
	at org.apache.myfaces.view.facelets.impl.TemplateContextImpl.includeDefinition(TemplateContextImpl.java:136)

**Comment by Johann-S** [comment]
I'm not sure but I think you choose the wrong projet to post your error :smile: 
See this : https://github.com/TheCoder4eu/BootsFaces-OSP

**Comment by rayidimurali** [comment]
Sorry, I did not realize that until you mentioned, there were multiple tabs opened and I was confused. Thank you :)
