### ISSUE TITLE
Compilation issue with gulp uglify and Alpha 4.4

### ISSUE THREAD

**Issue by djmtype** [twbs/bootstrap#20656]
On a fresh install of Yeoman [generator webapp](https://github.com/yeoman/generator-webapp), with Bootstrap v3.3.7, the JS compiles fine. 

However with Bootstrap 4.4 Alpha, I receive the following error. 

To troubleshoot the issue, I've also tried including just one of Alpha 4.4 JS files, and the error persists.

BTW, I am referencing all JS files from `/bower_components/bootstrap/js/src`

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
    at /Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:71:33
    at Array.forEach (native)
    at Object.exports.minify (/Users/me/Sites/mysite/node_modules/uglify-js/tools/node.js:66:15)
    at /Users/me/Sites/mysite/node_modules/gulp-uglify/minifier.js:65:22
    at trycatch (/Users/me/Sites/mysite/node_modules/gulp-uglify/minifier.js:15:12)
```

**Comment by djmtype** [comment]
I see it's best to call the JS from the `dist` directory instead
