### ISSUE TITLE
node/Windows build issue

### ISSUE THREAD

**Issue by patrickhlauke** [twbs/bootstrap#24034]
Using latest Node (6.11.3 LTS), even after updating all modules, when attempting to run the npm scripts I get the following error that prevents me from building locally:

> > bootstrap@4.0.0-beta js-minify-bundle D:\github\patrickhlauke\bootstrap
> uglifyjs --config-file build/uglifyjs.config.json --output dist/js/bootstrap.bundle.min.js dist/js/bootstrap.bundle.js
>
> Parse error at dist/js/bootstrap.js:20,0
const Util = (() => {
^
ERROR: Unexpected token: keyword (const)
    at JS_Parse_Error.get (eval at <anonymous> (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\tools\node.js:21:1), <anonymous>:79:23)
    at fatal (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:268:52)
    at run (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:225:9)
    at Object.<anonymous> (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:155:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Parse error at dist/js/bootstrap.bundle.js:19,0
const Util = (() => {
^
ERROR: Unexpected token: keyword (const)
    at JS_Parse_Error.get (eval at <anonymous> (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\tools\node.js:21:1), <anonymous>:79:23)
    at fatal (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:268:52)
    at run (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:225:9)
    at Object.<anonymous> (D:\github\patrickhlauke\bootstrap\node_modules\uglify-js\bin\uglifyjs:155:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by Johann-S** [comment]
strange :thinking: personnaly I use node `8.5.0` and no issue
but on travis everything works fine with node v4 and node v8

**Comment by patrickhlauke** [comment]
Tried Node 8.5 but that complains about missing SASS component for Win64

**Comment by bardiharborow** [comment]
@patrickhlauke I feel like we've been repeatedly messing you over in terms of Windows support, so I may try to get access to a Windows VM and start testing changes there. Maybe we can look into something AppVeyor as well.

**Comment by Johann-S** [comment]
I'm on Win10 too, but no issues 🤔

**Comment by patrickhlauke** [comment]
i admit that i'm probably the odd one out using windows here, always bringing up weird issues. when it works, though, it works great.

**Comment by patrickhlauke** [comment]
@Johann-S hmm, strange. is there any other npm housekeeping I should do? (i usually make sure to have reasonable recent node LTS installed, and then when hitting build problems run through the `npm install` etc steps at https://getbootstrap.com/docs/4.0/getting-started/build-tools/#tooling-setup)

**Comment by Johann-S** [comment]
Did you try to remove your `node_modules` folder ? and after a fresh `npm i` ?

**Comment by patrickhlauke** [comment]
whoah, doing `npm i -g npm` as a first step, then the usual `npm install` etc, fixed this. worth adding something to https://getbootstrap.com/docs/4.0/getting-started/build-tools/#tooling-setup to that effect?

**Comment by Johann-S** [comment]
It seems you hadn't `npm` in your PATH, I don't think so that's something very common to have `npm` in Windows PATH variable

**Comment by patrickhlauke** [comment]
no, `npm` is in my path. it just seems that it doesn't do the update check automatically

```
┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\redux\.config │
└────────────────────────────────────────────────────────────┘
```

**Comment by bardiharborow** [comment]
@patrickhlauke I've had lots of issues with earlier versions of npm (including possibly the version that ships with v6) even on Mac and Linux, so that doesn't surprise me. npm v5 and above seems to have stabilized certain things.

**Comment by XhmikosR** [comment]
I'm on Windows and have no issues. Generally, `rd /q /s node_modules && npm i` with the latest node 8.x.

**Comment by patrickhlauke** [comment]
should the above be added to the docs?

**Comment by XhmikosR** [comment]
Nah, it's general npm troubleshooting.

With npm 5 you should have such issues.

**Comment by XhmikosR** [comment]
... as long as you do `npm i` after package-lock.json has changed.

**Comment by patrickhlauke** [comment]
fair enough (though I did have the problem with npm 5, and even after doing `npm install`)
