### ISSUE TITLE
Cannot install v4 with bower

### ISSUE THREAD

**Issue by CoryAlbrecht** [twbs/bootstrap#24068]
Cannot install bootstrap v4 as per instructions at https://getbootstrap.com/docs/4.0/getting-started/download/#bower

Bower reports an EMALFORMED error

```
cory@VaporTrails[18:46:47]~/Development/Personal/Eclipse/Sudoku$ bower -V -f install bootstrap#v4-dev
bower underscore#^1.8.3        resolve https://github.com/jashkenas/underscore.git#^1.8.3
bower normalize-css#^7.0.0     resolve https://github.com/necolas/normalize.css.git#^7.0.0
bower bootstrap#v4-dev         resolve https://github.com/twbs/bootstrap.git#v4-dev
bower jquery-ui#^1.12.1        resolve https://github.com/components/jqueryui.git#^1.12.1
bower jquery#^3.2.1            resolve https://github.com/jquery/jquery-dist.git#^3.2.1
bower normalize-css#^7.0.0    download https://github.com/necolas/normalize.css/archive/7.0.0.tar.gz
bower underscore#^1.8.3       download https://github.com/jashkenas/underscore/archive/1.8.3.tar.gz
bower jquery-ui#^1.12.1       download https://github.com/components/jqueryui/archive/1.12.1.tar.gz
bower jquery#^3.2.1           download https://github.com/jquery/jquery-dist/archive/3.2.1.tar.gz
bower bootstrap#v4-dev        download https://github.com/twbs/bootstrap/archive/v4-dev.tar.gz
bower normalize-css#^7.0.0     extract archive.tar.gz
bower jquery#^3.2.1            extract archive.tar.gz
bower normalize-css#^7.0.0    resolved https://github.com/necolas/normalize.css.git#7.0.0
bower underscore#^1.8.3        extract archive.tar.gz
bower jquery-ui#^1.12.1        extract archive.tar.gz
bower underscore#^1.8.3       resolved https://github.com/jashkenas/underscore.git#1.8.3
bower bootstrap#v4-dev         extract archive.tar.gz
bower jquery#^3.2.1           resolved https://github.com/jquery/jquery-dist.git#3.2.1
bower jquery#>=1.6             resolve https://github.com/jquery/jquery-dist.git#>=1.6
bower jquery#>=1.6            download https://github.com/jquery/jquery-dist/archive/3.2.1.tar.gz
bower jquery#>=1.6             extract archive.tar.gz
bower jquery#>=1.6            resolved https://github.com/jquery/jquery-dist.git#3.2.1
bower jquery-ui#^1.12.1       resolved https://github.com/components/jqueryui.git#1.12.1
bower bootstrap#v4-dev      EMALFORMED Failed to read /tmp/cory/bower/ca4c50b905dc21ea17a10549a6f5944f-8948-FU48Fs/bower.json

Additional error details:
Unexpected token @

Stack trace:
SyntaxError: Unexpected token @
    at Object.parse (native)
    at /usr/local/lib/node_modules/bower/lib/node_modules/bower-json/lib/json.js:42:29
    at /usr/local/lib/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
From previous event:
    at readJson (/usr/local/lib/node_modules/bower/lib/util/readJson.js:17:6)
    at GitHubResolver.Resolver._readJson (/usr/local/lib/node_modules/bower/lib/core/resolvers/Resolver.js:180:12)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 4.2.6
OS: Linux 4.4.0-97-generic x64
```

Ubuntu+GNOME 16.04.3

**Comment by Johann-S** [comment]
you have to do do : `bower install bootstrap#v4.0.0-beta` with a release tag not a branch tag like you did : `bower -V -f install bootstrap#v4-dev`

**Comment by ljcusack** [comment]
I'm getting the same issue whilst using bootstrap-cli. Tried the suggested command and the issue remains:
```
l:y % bower install bootstrap#v4.0.0-beta
bower not-cached    https://github.com/twbs/bootstrap.git#4
bower resolve       https://github.com/twbs/bootstrap.git#4
bower not-cached    https://github.com/twbs/bootstrap.git#v4.0.0-beta
bower resolve       https://github.com/twbs/bootstrap.git#v4.0.0-beta
bower cached        https://github.com/HubSpot/tether.git#1.4.0
bower validate      1.4.0 against https://github.com/HubSpot/tether.git#^1.1.2
bower download      https://github.com/twbs/bootstrap/archive/v4.0.0-beta.tar.gz
bower download      https://github.com/twbs/bootstrap/archive/v4.0.0-beta.2.tar.gz
bower progress      bootstrap#4 received 2.2MB of 2.4MB downloaded, 92%
bower progress      bootstrap#v4.0.0-beta received 1.9MB
bower extract       bootstrap#4 archive.tar.gz
bower progress      bootstrap#v4.0.0-beta received 2.1MB
bower progress      bootstrap#v4.0.0-beta received 2.4MB
bower extract       bootstrap#v4.0.0-beta archive.tar.gz
bower resolved      https://github.com/twbs/bootstrap.git#4.0.0-beta
bower EMALFORMED    Failed to read /var/folders/tl/jc4dm03x1tl_22m95hrk5nrm0000gn/T/l/bower/ca4c50b905dc21ea17a10549a6f5944f-15552-BroElx/bower.json

Additional error details:
Unexpected token @ in JSON at position 0

**Comment by hebbet** [comment]
> Dropped Bower support as the package manager has been deprecated for alternatives (e.g., Yarn or npm). See bower/bower#2298 for details.

http://getbootstrap.com/docs/4.0/migration/#beta-2-changes

see also #23568

**Comment by solomonculaste** [comment]
@hebbet Why bootstrap 4 beta is removed from bower?
