### ISSUE TITLE
npm run dist gives an error

### ISSUE THREAD

**Issue by juh2** [twbs/bootstrap#24602]
I get an error when running npm run dist.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle bootstrap@4.0.0-beta~predist: bootstrap@4.0.0-beta
6 silly lifecycle bootstrap@4.0.0-beta~predist: no script for predist, continuing
7 info lifecycle bootstrap@4.0.0-beta~dist: bootstrap@4.0.0-beta
8 verbose lifecycle bootstrap@4.0.0-beta~dist: unsafe-perm in lifecycle true
9 verbose lifecycle bootstrap@4.0.0-beta~dist: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/juh/Projekte/Sites/www.generationenprojekt.de/themes/bootstrap-gp/bower_components/bootstrap/node_modules/.bin:/home/juh/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/home/juh/go/bin:/home/juh/.vimpkg/bin:/snap/bin
10 verbose lifecycle bootstrap@4.0.0-beta~dist: CWD: /home/juh/Projekte/Sites/www.generationenprojekt.de/themes/bootstrap-gp/bower_components/bootstrap
11 silly lifecycle bootstrap@4.0.0-beta~dist: Args: [ '-c', 'npm-run-all --parallel css js css-docs' ]
12 silly lifecycle bootstrap@4.0.0-beta~dist: Returned: code: 1  signal: null
13 info lifecycle bootstrap@4.0.0-beta~dist: Failed to exec dist script
14 verbose stack Error: bootstrap@4.0.0-beta dist: `npm-run-all --parallel css js css-docs`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid bootstrap@4.0.0-beta
16 verbose cwd /home/juh/Projekte/Sites/www.generationenprojekt.de/themes/bootstrap-gp/bower_components/bootstrap
17 error Linux 4.9.0-4-amd64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
19 error node v6.11.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bootstrap@4.0.0-beta dist: `npm-run-all --parallel css js css-docs`
22 error Exit status 1
23 error Failed at the bootstrap@4.0.0-beta dist script 'npm-run-all --parallel css js css-docs'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bootstrap package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all --parallel css js css-docs
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bootstrap
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bootstrap
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

npm install before gave me this warning:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/qunitjs/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN bootstrap@4.0.0-beta requires a peer of jquery@>=1.9.1 but none was installed.
npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none was installed.

```

**Comment by XhmikosR** [comment]
1. That is the old version
2. Bootstrap is no longer being published to Bower
3. After the above, prune your local node_modules and do `npm i` again.

If that doesn't fix your issue, no idea what else could be wrong, since as you can see Travis builds are OK.

**Comment by mdo** [comment]
Closing since this runs fine for us and it's outdated. Please keep commenting if there's more we can help with though!
