### ISSUE TITLE
The command npm run test is not working

### ISSUE THREAD

**Issue by revolutionnaire** [twbs/bootstrap#25330]
I am using a Chrome OS and I have Node JS and NPM installed properly, but whenever I run the commmand, it always tells me that:
`npm ERR! Failed at the bootstrap@4.0.0-beta.3 test script.`
`npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

I looked into the debug log file and couldn't understand this part:
`12 info lifecycle bootstrap@4.0.0-beta.3~test: Failed to exec test script`
`13 verbose stack Error: bootstrap@4.0.0-beta.3 test: 'npm-run-all dist js-test docs-compile docs-lint bundlesize'`
`13 verbose stack Exit status 126`
`13 verbose stack     at EventEmitter.<anonymous>
 (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)`
`13 verbose stack     at EventEmitter.emit (events.js:160:13)`
`13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:160:13)`
`13 verbose stack     at maybeClose (internal/child_process.js:943:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)`

**Comment by andresgalante** [comment]
It works here, try deleting node_modules folder, getting a fresh copy of bootstrap, do `npm install` and then `npm run test`

**Comment by mdo** [comment]
Yeah, I had similar issues last week if I recall and had to either nuke my `node_modules` or do that fancier update. I believe we changed node versions or something? It's working fine for me as well.

**Comment by client9** [comment]
same problem.   Bleeding edge macOS home-brew strikes again.

to my knowledge I have a clean virgin install of nodejs, and a fresh clone of home-brew.
```
$ /usr/local/Cellar/node/9.11.1/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run bundlesize

> bootstrap@4.1.0 bundlesize /Users/nickg/go/src/github.com/twbs/bootstrap
> bundlesize

 PASS  ./dist/css/bootstrap-grid.css: 3.84KB < maxSize 5KB (gzip) 

 PASS  ./dist/css/bootstrap-grid.min.css: 3.31KB < maxSize 5KB (gzip) 

 PASS  ./dist/css/bootstrap-reboot.css: 1.64KB < maxSize 3KB (gzip) 

 PASS  ./dist/css/bootstrap-reboot.min.css: 1.55KB < maxSize 3KB (gzip) 

 PASS  ./dist/css/bootstrap.css: 22.06KB < maxSize 25KB (gzip) 

 PASS  ./dist/css/bootstrap.min.css: 20.44KB < maxSize 21KB (gzip) 

 PASS  ./dist/js/bootstrap.bundle.js: 41.7KB < maxSize 45KB (gzip) 

 PASS  ./dist/js/bootstrap.bundle.min.js: 20.13KB < maxSize 25KB (gzip) 

 PASS  ./dist/js/bootstrap.js: 19.89KB < maxSize 20KB (gzip) 

 PASS  ./dist/js/bootstrap.min.js: 13.66KB < maxSize 15KB (gzip) 

 ERROR  Could not add github status.
        404: Not Found 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@4.1.0 bundlesize: `bundlesize`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.1.0 bundlesize script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nickg/.npm/_logs/2018-04-10T21_33_17_829Z-debug.log
```

```
 cat  /Users/nickg/.npm/_logs/2018-04-10T21_33_17_829Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.11.1/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bundlesize' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'prebundlesize', 'bundlesize', 'postbundlesize' ]
5 info lifecycle bootstrap@4.1.0~prebundlesize: bootstrap@4.1.0
6 info lifecycle bootstrap@4.1.0~bundlesize: bootstrap@4.1.0
7 verbose lifecycle bootstrap@4.1.0~bundlesize: unsafe-perm in lifecycle true
8 verbose lifecycle bootstrap@4.1.0~bundlesize: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/nickg/go/src/github.com/twbs/bootstrap/node_modules/.bin:/Users/nickg/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle bootstrap@4.1.0~bundlesize: CWD: /Users/nickg/go/src/github.com/twbs/bootstrap
10 silly lifecycle bootstrap@4.1.0~bundlesize: Args: [ '-c', 'bundlesize' ]
11 silly lifecycle bootstrap@4.1.0~bundlesize: Returned: code: 1  signal: null
12 info lifecycle bootstrap@4.1.0~bundlesize: Failed to exec bundlesize script
13 verbose stack Error: bootstrap@4.1.0 bundlesize: `bundlesize`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid bootstrap@4.1.0
15 verbose cwd /Users/nickg/go/src/github.com/twbs/bootstrap
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "bundlesize"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error bootstrap@4.1.0 bundlesize: `bundlesize`
22 error Exit status 1
23 error Failed at the bootstrap@4.1.0 bundlesize script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
