### ISSUE TITLE
Unusable with node

### ISSUE THREAD

**Issue by guimard** [twbs/bootstrap#28135]
OS: Linux Debian unstable

Hello,

bootstrap is packaged as node module but seems unusable with it _(JQuery fn() undefined)_. Example:
```shell
$ npm install bootstrap4
$ npm install jquery
$ node -e 'require("bootstrap")'
/tmp/node_modules/bootstrap/dist/js/bootstrap.js:121
    $.fn.emulateTransitionEnd = transitionEndEmulator;
                              ^

TypeError: Cannot set property 'emulateTransitionEnd' of undefined
    at setTransitionEndSupport (/tmp/node_modules/bootstrap/dist/js/bootstrap.js:121:31)
    at /tmp/node_modules/bootstrap/dist/js/bootstrap.js:220:3
    at /tmp/node_modules/bootstrap/dist/js/bootstrap.js:7:66
    at Object.<anonymous> (/tmp/node_modules/bootstrap/dist/js/bootstrap.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

Another test with jQuery:
```
$ node -e 'global.$ = require("jquery");require("bootstrap")'
/tmp/node_modules/bootstrap/dist/js/bootstrap.js:121
    $.fn.emulateTransitionEnd = transitionEndEmulator;
                              ^

TypeError: Cannot set property 'emulateTransitionEnd' of undefined
    at setTransitionEndSupport (/tmp/node_modules/bootstrap/dist/js/bootstrap.js:121:31)
    at /tmp/node_modules/bootstrap/dist/js/bootstrap.js:220:3
    at /tmp/node_modules/bootstrap/dist/js/bootstrap.js:7:66
    at Object.<anonymous> (/tmp/node_modules/bootstrap/dist/js/bootstrap.js:10:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```
Not important issue

**Comment by Johann-S** [comment]
Bootstrap isn't compatible with Node currently, because we need a `document` object.
But it's pretty weird it fails on this line:
```js
$.fn.emulateTransitionEnd = transitionEndEmulator;
```

because if jQuery is imported it shouldn't be the case

**Comment by Johann-S** [comment]
It seems that's because you do not import jQuery correctly in Node.js see:
https://www.npmjs.com/package/jquery#node

Anyway we don't plan to support to be used in a NodeJS server.
