### ISSUE TITLE
Scrollspy with real href="url" in navbar throws Javascript exception.

### ISSUE THREAD

**Issue by jenstroeger** [twbs/bootstrap#28171]
I think this is somewhat related to issue https://github.com/twbs/bootstrap/issues/27903, but it’s about the [Scrollspy](https://getbootstrap.com/docs/4.2/components/scrollspy/). Using a non-selector `href` in any of the `<a>` elements of the `<nav>` causes the following error:

```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'https://google.com/' is not a valid selector.
    at Object.getSelectorFromElement (https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:1466)
    at https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:46766
    at Array.map (<anonymous>)
    at n.t.refresh (https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:46740)
    at new n (https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:46381)
    at HTMLBodyElement.<anonymous> (https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:49266)
    at Function.each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:2765)
    at w.fn.init.each (https://code.jquery.com/jquery-3.3.1.slim.min.js:2:1438)
    at w.fn.init.n._jQueryInterface [as scrollspy] (https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:49218)
    at https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js:6:49678
```
I have a navbar with local navigation links, and a last menu item that links to a subdomain. I also think that this is a regression from BS 4.1 because that same navbar/scrollspy has worked there.

- Operating system and version: MacOS Mojave
- Browser and version: Chrome 71.0.3578.98
- Test case: Try it with the examples on the Bootstrap page.

**Comment by XhmikosR** [comment]
That's a duplicate. Generally try to use valid selectors, and wait for the next version which should bring back the previous behavior.
