### ISSUE TITLE
Module build failed with scss on _modal.scss

### ISSUE THREAD

**Issue by jmwierzbicki** [twbs/bootstrap#28879]
After updating project dependencies my bootstrap stopped compiling, i was getting:
```

ERROR in ./src/styles/base/all.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                                                               ^
      Undefined operation: "auto times 2".
      in C:\Users\jmwie\dev\npc\gui\node_modules\bootstrap\scss\_modal.scss (line 198, column 65)
    at runLoaders (C:\Users\jmwie\dev\npc\gui\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\jmwie\dev\npc\gui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\jmwie\dev\npc\gui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\jmwie\dev\npc\gui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (C:\Users\jmwie\dev\npc\gui\node_modules\sass-loader\lib\loader.js:55:13)
    at Object.done [as callback] (C:\Users\jmwie\dev\npc\gui\node_modules\neo-async\async.js:8077:18)
    at options.error (C:\Users\jmwie\dev\npc\gui\node_modules\node-sass\lib\index.js:294:32)
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...
```

which i was able to fix by changing this function inside _modal.scss:

```
// Scale up the modal
@include media-breakpoint-up(sm) {
  // Automatically set modal's width for larger viewports
  .modal-dialog {
    max-width: $modal-md;
    margin: $modal-dialog-margin-y-sm-up auto;
  }

  .modal-dialog-scrollable {
    max-height: calc(100% - #{$modal-dialog-margin-y-sm-up }* 2); // was #{$modal-dialog-margin-y-sm-up * 2 }

    .modal-content {
      max-height: calc(100vh - #{$modal-dialog-margin-y-sm-up }* 2);
    }
  }

  .modal-dialog-centered {
    min-height: calc(100% - #{$modal-dialog-margin-y-sm-up }* 2);

    &::before {
      height: calc(100vh - #{$modal-dialog-margin-y-sm-up }* 2);
    }
  }

  .modal-content {
    @include box-shadow($modal-content-box-shadow-sm-up);
  }

  .modal-sm { max-width: $modal-sm; }
}
```

**Comment by ysds** [comment]
Setting `$modal-dialog-margin-y-sm-up` to `auto` makes no sense and is not expected.

Why do you need to do that?

**Comment by jmwierzbicki** [comment]
Why centering modal window vertically does not make sense?

**Comment by ysds** [comment]
Even if it is `auto`, modals doesn't become vertical center.

You can use https://getbootstrap.com/docs/4.3/components/modal/#vertically-centered

**Comment by XhmikosR** [comment]
Closing due to lack of response. You can comment here and we can re-open the issue.

*This is an automated reply*
