### ISSUE TITLE
UncontrolledCollapse "SyntaxError '##toggler' is not a valid selector" test failure

### ISSUE THREAD

**Issue by akilman** [twbs/bootstrap#28885]
- Operating system and version macOS 10.14.5
- Browser and version Firefox 67.0 (64-bit) (however, issue occurs in unit tests)
- Test case - https://github.com/akilman/reactstrap-collapse-bug

In attempting to use the [UncontrolledCollapse](https://reactstrap.github.io/components/collapse/) component, I noticed it works like a charm when run on the browser but not during rendering for a test case. 

I was able to reproduce the behavior in [this repo](https://reactstrap.github.io/components/collapse/) which was a plain `create-react-app` with `bootstrap` and `reactstrap` installed. I copy/pasted the same `Example` from the docs noted above. And same behavior. Browser works just fine, test fails with the following error:

```    
SyntaxError: '##toggler' is not a valid selector

      at emit (node_modules/nwsapi/src/nwsapi.js:563:17)
      at Object._querySelectorAll [as select] (node_modules/nwsapi/src/nwsapi.js:1492:9)
      at findDOMElements (node_modules/reactstrap/lib/utils.js:239:28)
      at UncontrolledCollapse.componentDidMount (node_modules/reactstrap/lib/UncontrolledCollapse.js:55:48)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:17334:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:18736:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:149:14)
```

**Comment by akilman** [comment]
Sorry, wrong repo
