### ISSUE TITLE
JisonLexerError: Lexical error on line 1: Unrecognized text.

### ISSUE THREAD

**Issue by SpenzeR** [twbs/bootstrap#29751]
After upgrading from v4.3.1 to v4.4.0 I receive an error while running "npm run production".

"npm run dev" works as expected, only production builds fails.

```
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 1.6em + 0.75rem2px
^...........^
    at /css/global.css:9611:3
    at Object.parseError (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:1164:15)
    at Object.lexer_parseError [as parseError] (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:2297:44)
    at Object.lexer_next [as next] (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:3292:22)
    at Object.lexer_fastLex [as fastLex] (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:3367:18)
    at fastLex (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:1567:27)
    at Parser.parse (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/parser.js:1641:30)
    at /Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/lib/transform.js:30:30
    at walk (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:19:7)
    at ValueParser.walk (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/lib/transform.js:59:100)
    at /Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/index.js:25:51
    at /Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:131:17)
    at /Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/andrew/Sites/vpff/src/node_modules/postcss/lib/container.js:131:17)
    at /Users/andrew/Sites/vpff/src/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/Users/andrew/Sites/vpff/src/node_modules/cssnano/dist/index.js:31:51)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by SpenzeR** [comment]
Duplicate of #29743
