### ISSUE TITLE
Bootstrap + Parcel / Webpack error importing bootstrap/dist/css/bootstrap.css

### ISSUE THREAD

**Issue by yonatankarimish** [twbs/bootstrap#30109]
I created a new project, which uses Parcel as the web application bundler (https://parceljs.org/).
Using the following package.json:

```
{
  "name": "...",
  "version": "1.0.0",
  "repository": "...",
  "author": "Yonatan <yonatan@backbox.com>",
  "license": "MIT",
  "main": "web/index.js",
  "scripts": {...},
  "devDependencies": {
    "@babel/core": "~7.8.3",
    "@babel/preset-env": "~7.8.3",
    "@babel/preset-react": "~7.8.3",
    "eslint": "~6.8.0",
    "graceful-fs": "~4.1.15",
    "ncp": "~2.0.0",
    "parcel-bundler": "~1.12.4",
    "promise": "~8.0.1",
    "rimraf": "~3.0.1",
    "ssh2": "~0.8.4",
    "ssh2-utils": "~1.0.28",
    "stylus": "^0.54.7",
    "walk": "~2.3.9",
    "yargs": "~13.2.4"
  },
  "dependencies": {
    "axios": "~0.19.2",
    "bootstrap": "~4.1.3",
    "jquery": "~3.4.1",
    "popper.js": "~1.16.1",
    "react": "~16.12.0",
    "react-dom": "~16.12.0"
  },
  "browserslist": [
    ">0.25% and last 2 versions",
    "not ie 11",
    "not op_mini all"
  ]
}
```
When reducing the test case just to the main entry point (web/index.js), with negligible body and just two import statements:

```
import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.css';
```

loading the main html file throws the following error:
`Uncaught (in promise) Error: Cannot find module 'w265'`

removing the bootstrap/dist/css/bootstrap.css import, the page loads just fine, albeit without the missing styles.

Baffled, I thought this might be a problem with Parcel, and switched to webpack.
Using an identical package.json, except for:
```
"devDependencies": {
  "@babel/core": "~7.8.3",
  "@babel/preset-env": "~7.8.3",
  "@babel/preset-react": "~7.8.3",
  "babel-loader": "~8.0.6",
  "css-loader": "~3.4.2",
  "eslint": "~6.8.0",
  "graceful-fs": "~4.1.15",
  "html-webpack-plugin": "~3.2.0",
  "html-webpack-template": "~6.2.0",
  "ncp": "~2.0.0",
  "parcel-bundler": "~1.12.4",
  "promise": "~8.0.1",
  "rimraf": "~3.0.1",
  "ssh2": "~0.8.4",
  "ssh2-utils": "~1.0.28",
  "style-loader": "~1.1.3",
  "stylus": "~0.54.7",
  "stylus-loader": "~3.0.2",
  "url-loader": "~3.0.0",
  "walk": "~2.3.9",
  "webpack": "~4.41.5",
  "webpack-cli": "~3.3.10",
  "yargs": "~13.2.4"
}
```

and the following webpack.config.js:
```
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const config = {
  entry: './web/index.js',
  output: {
    path: path.resolve(__dirname, '/src/main/resources/web'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(styl|css)$/,
        use: [
          'style-loader',
          'css-loader',
          'stylus-loader'
        ]
      },
      {
        test: /\.(png|jpg|jpeg|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              mimetype: 'image/png'
            }
          }
        ]
      }
    ]
  },
  resolve: {
    extensions: [
      '.js',
      '.jsx'
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
        template: require('html-webpack-template'),
        inject: false,
        appMountId: 'app',
        filename: 'index.html'
      })
  ]
};

module.exports = config;
```

I received the following error:
```
webpack -p
Hash: dc8527936e2bab5557e8
Version: webpack 4.41.5
Time: 5808ms
Built at: 01/30/2020 8:43:48 PM
 3 assets
Entrypoint main = runtime.09bc9f506d40348732e5.js vendors.af3cfd443620d5ff6668.js main.8247da5c5fb3f7a08c0a.js
[22] (webpack)/buildin/global.js 472 bytes {2} [built]
[42] ./web/app/app.styl 608 bytes {0} [built]
[43] ./node_modules/css-loader/dist/cjs.js!./node_modules/stylus-loader!./web/app/app.styl 799 bytes {0} [built]
[44] ./web/index.styl 601 bytes {0} [built]
[45] ./node_modules/css-loader/dist/cjs.js!./node_modules/stylus-loader!./web/index.styl 1.81 KiB {0} [built]
[47] ./web/assets/background.jpg 93.2 KiB {0} [built]
[48] ./web/index.js + 3 modules 250 KiB {0} [built]
     | ./web/index.js 283 bytes [built]
     | ./web/app/app.js 1.39 KiB [built]
     | ./web/assets/f5_logo.png 61.4 KiB [built]
     | ./web/assets/engine_logo.png 187 KiB [built]
    + 42 hidden modules

ERROR in ./node_modules/bootstrap/dist/css/bootstrap.css (./node_modules/css-loader/dist/cjs.js!./node_modules/stylus-loader!./node_modules/bootstrap/dist/css/bootstrap.css)
Module build failed (from ./node_modules/stylus-loader/index.js):
ParseError: [project_root]\node_modules\bootstrap\dist\css\bootstrap.css:2291:571
   2287|
   2288| .was-validated .custom-select:valid, .custom-select.is-valid {
   2289|   border-color: #28a745;
   2290|   padding-right: calc(0.75em + 2.3125rem);
   2291|   background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right 0.75rem center/8px 10px, url("data:image/svg+xm
l,%3csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8' viewBox='0 0 8 8'%3e%3cpath fill='%2328a745' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3e%3c/svg%3e") #fff no-repeat center right
 1.75rem/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem);
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------^
   2292| }
   2293|
   2294| .was-validated .custom-select:valid:focus, .custom-select.is-valid:focus {

expected ")", got ";"

    at Parser.error ([project_root]\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect ([project_root]\node_modules\stylus\lib\parser.js:287:12)
    at Parser.functionCall ([project_root]\node_modules\stylus\lib\parser.js:1810:10)
    at Parser.primary ([project_root]\node_modules\stylus\lib\parser.js:2291:18)
    at Parser.member ([project_root]\node_modules\stylus\lib\parser.js:2174:21)
    at Parser.subscript ([project_root]\node_modules\stylus\lib\parser.js:2152:21)
    at Parser.unary ([project_root]\node_modules\stylus\lib\parser.js:2143:17)
    at Parser.defined ([project_root]\node_modules\stylus\lib\parser.js:2115:21)
    at Parser.multiplicative ([project_root]\node_modules\stylus\lib\parser.js:2089:21)
    at Parser.additive ([project_root]\node_modules\stylus\lib\parser.js:2074:21)
    at Parser.range ([project_root]\node_modules\stylus\lib\parser.js:2058:21)
    at Parser.relational ([project_root]\node_modules\stylus\lib\parser.js:2037:21)
    at Parser.in ([project_root]\node_modules\stylus\lib\parser.js:2021:21)
    at Parser.equality ([project_root]\node_modules\stylus\lib\parser.js:2006:23)
    at Parser.typecheck ([project_root]\node_modules\stylus\lib\parser.js:1990:21)
    at Parser.logical ([project_root]\node_modules\stylus\lib\parser.js:1977:21)
    at Parser.ternary ([project_root]\node_modules\stylus\lib\parser.js:1961:21)
    at Parser.negation ([project_root]\node_modules\stylus\lib\parser.js:1953:17)
    at Parser.expression ([project_root]\node_modules\stylus\lib\parser.js:1932:24)
    at Parser.list ([project_root]\node_modules\stylus\lib\parser.js:1917:24)
    at Parser.property ([project_root]\node_modules\stylus\lib\parser.js:1596:22)
    at Parser.ident ([project_root]\node_modules\stylus\lib\parser.js:1538:25)
    at Parser.stmt ([project_root]\node_modules\stylus\lib\parser.js:843:30)
    at Parser.statement ([project_root]\node_modules\stylus\lib\parser.js:750:21)
    at Parser.block ([project_root]\node_modules\stylus\lib\parser.js:925:21)
    at Parser.selector ([project_root]\node_modules\stylus\lib\parser.js:1640:24)
    at Parser.stmt ([project_root]\node_modules\stylus\lib\parser.js:862:31)
    at Parser.statement ([project_root]\node_modules\stylus\lib\parser.js:750:21)
    at Parser.parse ([project_root]\node_modules\stylus\lib\parser.js:236:25)
    at Renderer.render ([project_root]\node_modules\stylus\lib\renderer.js:80:22)
    at [project_root]\node_modules\stylus-loader\index.js:167:12
    at tryCatchReject ([project_root]\node_modules\when\lib\makePromise.js:840:30)
    at runContinuation1 ([project_root]\node_modules\when\lib\makePromise.js:799:4)
    at Fulfilled.when ([project_root]\node_modules\when\lib\makePromise.js:590:4)
    at Pending.run ([project_root]\node_modules\when\lib\makePromise.js:481:13)
    at Scheduler._drain ([project_root]\node_modules\when\lib\Scheduler.js:62:19)
 @ ./node_modules/bootstrap/dist/css/bootstrap.css 2:26-118
 @ ./web/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 2 hidden modules
error Command failed with exit code 2.
```

I tried reverting to an earlier bootstrap version, and after some trial and error, version 4.1.3 managed to bundle with no errors. version 4.2.1 produces the same error.

Reproduced on:
Windows 10 Pro version 10.0.17763
Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) (currently the latest)

**Comment by mdo** [comment]
I'm not experiences with Webpack or Parcel, can anyone else help? If not, you may need to jump into our Slack or StackOverflow.

**Comment by ysds** [comment]
Don't use `stylus-loader` to load a CSS file. and closing this per mdo's comment.

**Comment by antergos98** [comment]
I had the same exact issue after upgrading bootstrap from 4.1 to 4.6. My fix was to move all css import in a new css file called "packages.css" and import this file in my app.js file before the stylus file.

```javascript
// Import stuff
import './styles/packages.css'
import './styles/main.styl'

// Rest of my code
```

My packages.css looks like this
```css
@import "../../node_modules/bootstrap/dist/css/bootstrap.css";
@import "../../node_modules/bootstrap-vue/dist/bootstrap-vue.css";
@import "~loaders.css/loaders.css";
@import "~vue-datetime/dist/vue-datetime.css";
@import "~vue-wysiwyg/dist/vueWysiwyg.css";
```

and now there no more css imports in my stylus file and everything is working fine.
