### ISSUE TITLE
ESLint fails to load unicorn plugin

### ISSUE THREAD

**Issue by ffoodd** [twbs/bootstrap#30169]
I'm currently stuck with ESLint (while running `js-lint`), which keeps failing since my last `pull` in `master`.

I tried everything I could: deleting `node_modules` and install again, etc. Nothing works for now.

Here is the trace:

```sh
SyntaxError: Failed to load plugin 'unicorn' declared in '.eslintrc.json': Invalid regular expression: /^(?<integerPart>[+-]?\d*)(?:(?<dotAndZeroes>\.0*)|(?<dotAndDigits>\.\d*[1-9])0+)(?<scientificNotationSuffix>e[+-]?\d+)?$/: Invalid group
Referenced from: /home/gael/Workspace/bootstrap/.eslintrc.json
    at Object.<anonymous> (/home/gael/Workspace/bootstrap/node_modules/eslint-plugin-unicorn/rules/no-zero-fractions.js:12:42)
    at Module._compile (/home/gael/Workspace/bootstrap/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/home/gael/Workspace/bootstrap/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at module.exports (/home/gael/Workspace/bootstrap/node_modules/import-modules/index.js:47:29)
    at Object.<anonymous> (/home/gael/Workspace/bootstrap/node_modules/eslint-plugin-unicorn/index.js:6:9)
```

Does anyone get this error too?

**Comment by XhmikosR** [comment]
Nope.

Install the latest Node.js 12.x LTS, `npm cache clean -fg && rm -rf ./node_modules && npm i` and it should work. If not jump on Slack and ping me

**Comment by ffoodd** [comment]
@XhmikosR It works, thanks! Probably related to the cache.

**Comment by Okeyemi** [comment]
1 am currently having this error
please help me out
ERROR in Failed to load plugin 'unicorn' declared in '.eslintrc.js » @nuxtjs/eslint-config': Cannot find module 'node:path'
Require stack:
- C:\Users\PC\logistics-website\node_modules\eslint-plugin-unicorn\rules\utils\rule.js
- C:\Users\PC\logistics-website\node_modules\eslint-plugin-unicorn\index.js
- C:\Users\PC\logistics-website\node_modules\@eslint\eslintrc\dist\eslintrc.cjs

**Comment by julien-deramond** [comment]
@Okeyemi This issue is already closed. You will have more chances of having an answer if you create a [new discussion](https://github.com/twbs/bootstrap/discussions/new).

**Comment by arpanEnbake** [comment]
@Okeyemi Please try to install this
https://www.npmjs.com/package/eslint-plugin-unicorn
```
npm i eslint-plugin-unicorn --save-dev --force
```
force is optional
