### ISSUE TITLE
Production build error since 4.4.0 related to modal and calc()

### ISSUE THREAD

**Issue by nmeirik** [twbs/bootstrap#30974]
I am experiencing an error when building for production using Webpack Encore. The error appears to be reproducable on 4.4.0 and above, but does not occur on 4.3.1. It can also be worked around on 4.4.0 and above by not including `node_modules/bootstrap/scss/_modal.scss`.

When building for production using the command `./node_modules/.bin/encore production` I experience the following error:

```
JisonParserError: Parse error on line 1: 
1rem 0 1rem 0 -...
-----^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "NUMBER"
    at /app/app.4cfdaf55.css:6158:3
    at Parser.parseError (/app/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Parser.parse (/app/node_modules/postcss-calc/dist/parser.js:1716:30)
    at /app/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/app/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/app/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/app/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/app/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at /app/node_modules/postcss-calc/dist/index.js:27:32
    at /app/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/app/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/app/node_modules/postcss/lib/container.js:131:17)
    at /app/node_modules/postcss/lib/container.js:148:24
    at Root.each (/app/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/app/node_modules/postcss/lib/container.js:131:17)
    at /app/node_modules/postcss-calc/dist/index.js:23:9
    at initializePlugin (/app/node_modules/cssnano/dist/index.js:31:51)
```

The error appears to be coming from attempting to generate border-radius for either `.modal-header` og `.modal-footer` (or probably both).

I suspect the error might be related to the following highlight for version 4.4.0:

> New add() and subtract() functions for avoiding errors and zero values from CSS's built in calc feature.

**Comment by XhmikosR** [comment]
Somewhere you are missing something but without a test repo, there's not a lot to tell.

Since it works for core and everything else, I suggest that you look further how you import our Sass files.

**Comment by nmeirik** [comment]
In which case I'm sorry for the false report. I'll look more closely into it when I find the time.
