### ISSUE TITLE
v5: shift-color() not working correctly with dark default link color?

### ISSUE THREAD

**Issue by marcelmoreau** [twbs/bootstrap#32949]
If I want a dark color as my default link color (e.g. `#111111`), I would want its hover state to lighten the color instead of darkening it. It would appear that v5 accounts for this in its variables file, using the `shift-color()` function. 
```
$link-color: $primary !default;
$link-decoration: underline !default;
$link-shade-percentage: 20% !default;
$link-hover-color: shift-color($link-color, $link-shade-percentage) !default;
$link-hover-decoration: null !default;
```
According to `shift-color()`’s [comment](https://github.com/twbs/bootstrap/blob/v5.0.0-beta1/scss/_functions.scss#L164) , it should _“Shade the color if the weight is positive, else tint it_”. This sounds perfect and is exactly what I hope for. But if I pass a negative percentage like `-20%` to `$link-shade-percentage` in hopes of tinting it, I get a Sass compilation error: `$weight: Expected -20% to be within 0% and 100%`. 

This aligns with that Sass says, that [`mix()` only accepts 0% - 100% weight](https://sass-lang.com/documentation/modules/color#mix), but I don't know. Am I doing this wrong? Thanks for your work getting v5 out!

**Comment by ffoodd** [comment]
Works great in our core (used in alerts, tables and list-groups) and made [a reduced test case on Sassmeister]—works great too.

May I ask what tool you're using to run Sass?

**Comment by marcelmoreau** [comment]
Sassmeister is buggy for me but you're right, it looks fine [in a codepen of your same code](https://codepen.io/marcelmoreau/pen/rNWaRXX)

Someone could probably close this ticket – I will close it tonight if no one else does.

I am running Laravel Mix 5.0.9 and I see references to Sass Loader (I am on 8.0.2) in my error output, so perhaps I'll try to update that, use another package, or I don't know what.
```
ERROR in ./resources/scss/main.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $weight: Expected -20% to be within 0% and 100%.
    ╷
161 │   @return mix(black, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap/scss/_functions.scss 161:11            shade-color()
  node_modules/bootstrap/scss/helpers/_colored-links.scss 8:68  @import
  node_modules/bootstrap/scss/_helpers.scss 2:9                 @import
  resources/scss/vendor/_bootstrap.scss 17:9                    @import
  resources/scss/vendor/__vendor-dir.scss 1:9                   @import
  /Users/marcel/Sites/git/foobar/resources/scss/main.scss 14:9                                                    root stylesheet
    at /Users/marcel/Sites/git/foobar/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/marcel/Sites/git/foobar/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/marcel/Sites/git/foobar/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/marcel/Sites/git/foobar/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/marcel/Sites/git/foobar/node_modules/sass-loader/dist/index.js:73:7
```
All that said, `$link-shade-percentage` might not be the best variable name, as it implies a link would always be shaded and not tinted. Someone might consider renaming that. I can open another issue if need be.

**Comment by ffoodd** [comment]
Could be renamed indeed, feel free to open a PR or suggest anything in a new issue.

**Comment by Boberro** [comment]
I believe the indeed is a bug regarding $link-shade-percentage variable. Just like @marcelmoreau wanted to use it, it's shading or tinting a link _shift-color_ function, but it's also used in helpers/_colored-links.scss and this use case does not take negative values into account.

helpers/_colored-links.scss line 8:
`color: if(color-contrast($value) == $color-contrast-light, shade-color($value, $link-shade-percentage), tint-color($value, $link-shade-percentage));`

**Comment by ffoodd** [comment]
Indeed, the goal is the same but the approach diverges. The variable is not the bug, but there's something to clarify and improve for sure.

**Comment by DaleyKD** [comment]
When I try to set `$link-shade-percentage: -20%;` in hopes of lightening my link hover color, node-sass gives me:

```
ERROR in ./styles/app.scss (./styles/app.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[0].use[3]!./styles/app.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: argument `$weight` of `mix($color-1, $color-2, $weight: 50%)` must be between -0 and 100
        on line 212 of node_modules/bootstrap/scss/_functions.scss, in function `mix`
        from line 212 of node_modules/bootstrap/scss/_functions.scss, in function `shade-color`
        from line 8 of node_modules/bootstrap/scss/helpers/_colored-links.scss, in function `if`
        from line 8 of node_modules/bootstrap/scss/helpers/_colored-links.scss
        from line 2 of node_modules/bootstrap/scss/_helpers.scss
        from line 49 of node_modules/bootstrap/scss/bootstrap.scss
        from line 19 of styles/app.scss
>>   @return mix(black, $color, $weight);

   ----------^

SassError: SassError: argument `$weight` of `mix($color-1, $color-2, $weight: 50%)` must be between -0 and 100
        on line 212 of node_modules/bootstrap/scss/_functions.scss, in function `mix`
        from line 212 of node_modules/bootstrap/scss/_functions.scss, in function `shade-color`
        from line 8 of node_modules/bootstrap/scss/helpers/_colored-links.scss, in function `if`
        from line 8 of node_modules/bootstrap/scss/helpers/_colored-links.scss
        from line 2 of node_modules/bootstrap/scss/_helpers.scss
        from line 49 of node_modules/bootstrap/scss/bootstrap.scss
        from line 19 of styles/app.scss
>>   @return mix(black, $color, $weight);

   ----------^

    at Object.callback (C:\src\ClientApp\node_modules\sass-loader\dist\index.js:54:16)
    at Object.done [as callback] (C:\src\ClientApp\node_modules\neo-async\async.js:8069:18)
    at options.error (C:\src\ClientApp\node_modules\node-sass\lib\index.js:293:32)
 @ ./styles/app.scss
```

Just figured I'd add my $0.02.

**Comment by OleksiiPrykhodko** [comment]
> If I want a dark color as my default link color (e.g. `#111111`), I would want its hover state to lighten the color instead of darkening it. It would appear that v5 accounts for this in its variables file, using the `shift-color()` function.
> 
> ```
> $link-color: $primary !default;
> $link-decoration: underline !default;
> $link-shade-percentage: 20% !default;
> $link-hover-color: shift-color($link-color, $link-shade-percentage) !default;
> $link-hover-decoration: null !default;
> ```
> 
> According to `shift-color()`’s [comment](https://github.com/twbs/bootstrap/blob/v5.0.0-beta1/scss/_functions.scss#L164) , it should _“Shade the color if the weight is positive, else tint it_”. This sounds perfect and is exactly what I hope for. But if I pass a negative percentage like `-20%` to `$link-shade-percentage` in hopes of tinting it, I get a Sass compilation error: `$weight: Expected -20% to be within 0% and 100%`.
> 
> This aligns with that Sass says, that [`mix()` only accepts 0% - 100% weight](https://sass-lang.com/documentation/modules/color#mix), but I don't know. Am I doing this wrong? Thanks for your work getting v5 out!

I found how to solve that problem.  I'm surprised no one has written about it yet. 
All you need to do is change the SCSS method from 
old one 
$link-hover-color:                        shift-color($link-color, $link-shade-percentage)
to the new one
$link-hover-color:                        transparentize($primary, .5);

**Comment by DaleyKD** [comment]
@julien-deramond : Any update on this? It looks like it's Need Review in 5.3.0, but I'm not sure if it'll make it or not.

**Comment by Komald** [comment]
> 

transparentize() worked for me.
