### ISSUE TITLE
False-detecting jQuery (v5)

### ISSUE THREAD

**Issue by williamd5** [twbs/bootstrap#33396]
Linux Ubuntu 20.04.2 LTS
Chrome 89

I have a small JS file that implements a function called `$` and serves as a very very basic version of jQuery for me to use. I believe the Bootstrap bundle 5.0.0-beta2 false-detects this as jQuery and tries to use it for dropdowns. I do not have a variable named jQuery or anything like that.

When clicking on a dropdown I get the following error:
> Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': 'function(t){return"applyStyles"===t.name&&!1===t.enabled}' is not a valid selector.

Dropdown HTML:
```html
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
```

This error is thrown at my `$(el).find()` method, according to the browser console.

**Comment by williamd5** [comment]
The error stack continues as follows:
```
    at o.r.show (bs.js:6:42376)
    at o.r.toggle (bs.js:6:41628)
    at Function.o.dropdownInterface (bs.js:6:45516)
    at HTMLButtonElement.<anonymous> (bs.js:6:48035)
    at HTMLDocument.i (bs.js:6:4661)
```

**Comment by williamd5** [comment]
Turns out it was a bug in my code which was overriding the default `.find()` method in `Array`
