### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Eoras** [twbs/bootstrap#35708]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, 

I'm using Symfony with WebpackEncore, and when i'm using MODALS with bootstrap, with the last update 5.1.3 of Bootstrap (installed with npm install bootstrap) i have a issue with modal :

```
bootstrap.esm.js:3131 Uncaught TypeError: Cannot read properties of null (reading 'hide')
    at HTMLButtonElement.<anonymous> (bootstrap.esm.js:3131:1)
    at HTMLDocument.handler (bootstrap.esm.js:387:1)
```

I tried to revert the version to 5.1.0 and this worked back. What happen with the 5.1.3 ? Something changed ?

My js file is compiled with webpack.

``` JS FILE : 
const $ = require('jquery');
require('bootstrap');

// any CSS you import will output into a single css file (app.css in this case)
import './styles/app.scss';

// start the Stimulus application
import './bootstrap';
```

Thanks for your help

### Reduced test cases

See describe the issue

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3

**Comment by XhmikosR** [comment]
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details.

*This is an automated reply*
