### ISSUE TITLE
Example "Customize > Color > Generating utilities" from the doc is missing import statement

### ISSUE THREAD

**Issue by jrbecart** [twbs/bootstrap#36241]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In https://getbootstrap.com/docs/5.1/customize/color/#generating-utilities

Following example is missing `@import "bootstrap/scss/maps";`

```javascript
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";

$all-colors: map-merge-multiple($blues, $indigos, $purples, $pinks, $reds, $oranges, $yellows, $greens, $teals, $cyans);

$utilities: map-merge(
  $utilities,
  (
    "color": map-merge(
      map-get($utilities, "color"),
      (
        values: map-merge(
          map-get(map-get($utilities, "color"), "values"),
          (
            $all-colors
          ),
        ),
      ),
    ),
  )
);

@import "bootstrap/scss/utilities/api";
```

Should be:

```javascript
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/utilities";

$all-colors: map-merge-multiple($blues, $indigos, $purples, $pinks, $reds, $oranges, $yellows, $greens, $teals, $cyans);

$utilities: map-merge(
  $utilities,
  (
    "color": map-merge(
      map-get($utilities, "color"),
      (
        values: map-merge(
          map-get(map-get($utilities, "color"), "values"),
          (
            $all-colors
          ),
        ),
      ),
    ),
  )
);

@import "bootstrap/scss/utilities/api";
```

### Reduced test cases

```shell
# node compile.js

undefined:1
throw error;
^

sass.Exception [Error]: Undefined variable.
    ╷
153 │       values: $utilities-border-colors
    │               ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  bootstrap/scss/_utilities.scss 153:15  @import
  style.scss 5:9                         root stylesheet
    at Object.wrapException (/home/user/temp/scss/node_modules/sass/sass.dart.js:1254:17)
    at _EvaluateVisitor1.visitVariableExpression$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:80377:15)
    at VariableExpression0.accept$1$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:97528:22)
    at VariableExpression0.accept$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:97531:19)
    at _EvaluateVisitor1.visitMapExpression$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:80544:33)
    at MapExpression0.accept$1$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:86224:22)
    at MapExpression0.accept$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:86227:19)
    at _EvaluateVisitor1.visitMapExpression$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:80544:33)
    at MapExpression0.accept$1$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:86224:22)
    at MapExpression0.accept$1 (/home/user/temp/scss/node_modules/sass/sass.dart.js:86227:19)
```

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment]
Nothing is missing in the docs—v5.1.x doesn't have this file, only v5.2.x will, and that version has yet to be release.

**Comment by iKorich** [comment]
i got that error on update from 5.3.1 to 5.2

**Comment by wendellpbarreto** [comment]
I also got that error on update from 5.1.3 to 5.2 yesterday

**Comment by Guilherme-Knorst** [comment]
Just import --> @import "bootstrap/scss/maps";
