### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by python-coding-404** [twbs/bootstrap#36262]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I tried to host the docs local but I got this error 
on node version v10.19.0
> hugo-bin@0.85.3 postinstall /home/zander/bootstrap/node_modules/hugo-bin
> rimraf vendor && node lib/install.js

/home/zander/bootstrap/node_modules/hugo-bin/lib/install.js:1
import path from 'node:path';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hugo-bin@0.85.3 postinstall: `rimraf vendor && node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hugo-bin@0.85.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_02_922Z-debug.log
when i test it
this happen
> bootstrap@5.1.3 test /home/zander/bootstrap
> npm-run-all lint dist js-test docs-build docs-lint

> bootstrap@5.1.3 lint /home/zander/bootstrap
> npm-run-all --aggregate-output --continue-on-error --parallel js-lint css-lint lockfile-lint

Oops! Something went wrong! :(

ESLint: 8.13.0

TypeError: Module.createRequire is not a function
    at Object.<anonymous> (/home/zander/bootstrap/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2383:26)
    at Module._compile (/home/zander/bootstrap/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/zander/bootstrap/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/zander/bootstrap/node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
    at Module._compile (/home/zander/bootstrap/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bootstrap@5.1.3 js-lint: `eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 js-lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_54_958Z-debug.log

> bootstrap@5.1.3 js-lint /home/zander/bootstrap
> eslint --cache --cache-location .cache/.eslintcache --report-unused-disable-directives .

> bootstrap@5.1.3 lockfile-lint /home/zander/bootstrap
> lockfile-lint --allowed-hosts npm --allowed-schemes https: --empty-hostname false --type npm --path package-lock.json

 ✔ No issues detected

/home/zander/bootstrap/node_modules/find-unused-sass-variables/cli.js:3
import fs from 'node:fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.1.3 css-lint-vars: `fusv scss/ site/assets/scss/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 css-lint-vars script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_56_817Z-debug.log
TypeError: [files].flat is not a function
    at standalone (/home/zander/bootstrap/node_modules/stylelint/lib/standalone.js:159:25)
    at module.exports (/home/zander/bootstrap/node_modules/stylelint/lib/cli.js:484:9)
    at Object.<anonymous> (/home/zander/bootstrap/node_modules/stylelint/bin/stylelint.js:8:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.1.3 css-lint-stylelint: `stylelint "**/*.{css,scss}" --cache --cache-location .cache/.stylelintcache --rd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 css-lint-stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_58_302Z-debug.log
ERROR: "css-lint-stylelint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.1.3 css-lint: `npm-run-all --aggregate-output --continue-on-error --parallel css-lint-*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 css-lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_58_388Z-debug.log

> bootstrap@5.1.3 css-lint /home/zander/bootstrap
> npm-run-all --aggregate-output --continue-on-error --parallel css-lint-*

> bootstrap@5.1.3 css-lint-vars /home/zander/bootstrap
> fusv scss/ site/assets/scss/

> bootstrap@5.1.3 css-lint-stylelint /home/zander/bootstrap
> stylelint "**/*.{css,scss}" --cache --cache-location .cache/.stylelintcache --rd

ERROR: "css-lint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.1.3 lint: `npm-run-all --aggregate-output --continue-on-error --parallel js-lint css-lint lockfile-lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_58_512Z-debug.log
ERROR: "lint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap@5.1.3 test: `npm-run-all lint dist js-test docs-build docs-lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap@5.1.3 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zander/.npm/_logs/2022-05-02T18_27_58_608Z-debug.log
npm log is 
4 verbose run-script [ 'predocs-serve', 'docs-serve', 'postdocs-serve' ]
5 info lifecycle bootstrap@5.1.3~predocs-serve: bootstrap@5.1.3
6 info lifecycle bootstrap@5.1.3~docs-serve: bootstrap@5.1.3
7 verbose lifecycle bootstrap@5.1.3~docs-serve: unsafe-perm in lifecycle true
8 verbose lifecycle bootstrap@5.1.3~docs-serve: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/zander/bootstrap/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/dotnet/:/mnt/c/Users/Zander is a coder/AppData/Local/Microsoft/WindowsApps:/snap/bin
9 verbose lifecycle bootstrap@5.1.3~docs-serve: CWD: /home/zander/bootstrap
10 silly lifecycle bootstrap@5.1.3~docs-serve: Args: [ '-c', 'hugo server --port 9001 --disableFastRender' ]
11 info lifecycle bootstrap@5.1.3~docs-serve: Failed to exec docs-serve script
12 verbose stack Error: bootstrap@5.1.3 docs-serve: `hugo server --port 9001 --disableFastRender`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid bootstrap@5.1.3
14 verbose cwd /home/zander/bootstrap
15 verbose Linux 4.4.0-19041-Microsoft
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "docs-serve"
17 verbose node v10.19.0
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error bootstrap@5.1.3 docs-serve: `hugo server --port 9001 --disableFastRender`
23 error spawn ENOENT
24 error Failed at the bootstrap@5.1.3 docs-serve script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
also npm version is 6.14.4

### Reduced test cases

this is not a front-end issue.

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment]
> on node version v10.19.0

I let the maintainers confirm but Node 16 should be used (this is the one used in GitHub workflows; see https://github.com/twbs/bootstrap/blob/main/.github/workflows/browserstack.yml).
I believe that Node 14 still works but is not the preferred version since it is in [maintenance status](https://nodejs.org/en/about/releases/).

**Comment by GeoSot** [comment]
Thank you @julien-deramond. You are right on this 🤗 
Better use at least the oldest active version

**Comment by python-coding-404** [comment]
i can't install ver 
16 through apt

**Comment by ffoodd** [comment]
apt is not the best way to install Node on Ubuntu, either use the downloadable binary or install nvm (or equivalent) to handle your Node versions.
