### ISSUE TITLE
function _isWithActiveTrigger in tooltip.js is causing an uncaught error

### ISSUE THREAD

**Issue by njmkramer** [twbs/bootstrap#37474]
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Uncaught TypeError: Cannot convert undefined or null to object
at Function.values ()
at Popover._isWithActiveTrigger (tooltip.js:549:19)
at complete (tooltip.js:279:16)
at execute (index.js:254:5)
at HTMLDivElement.handler (index.js:276:5)
at triggerTransitionEnd (index.js:98:11)
at index.js:282:7

This happens when multiple elements have a popover or a popover is attached to a new element and fast switching hover on elements.

### Reduced test cases

suggestion:
_isWithActiveTrigger() {
if(typeof this._activeTrigger == 'undefined' || this._activeTrigger === null){
return false;
}
return Object.values(this._activeTrigger).includes(true)
}

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.2

**Comment by njmkramer** [comment]
Reduced test:

https://js-cq37dw.stackblitz.io/

Focus as fast as you can different inputs and hover at the same time, enter a value, at some point the error will occur.
Tested on Chrome version: 107.0.5304.107
Bootstrap 5.2.2
@popperjs/core 2.11.6

**Comment by njmkramer** [comment]
Hi @julien-deramond, see my previous comment for reduced test/live demo.

**Comment by njmkramer** [comment]
Hi @julien-deramond any progress on this issue?

best regards

**Comment by hyphen81** [comment]
Running into this as well..

**Comment by GeoSot** [comment]
As much as I 've tested till now, I cannot replicate the issue :confused:

**Comment by njmkramer** [comment]
![_isWithActiveTrigger ](https://user-images.githubusercontent.com/98040092/212662398-eaced9ff-47b8-4bab-927f-057904258ee5.jpg)


fix:
if (this!== null) {
if (
typeof this._activeTrigger != 'undefined' &&
typeof this._activeTrigger.hover == 'undefined'
) {
this._activeTrigger.hover = false;
}
}

**Comment by njmkramer** [comment]
![_isWithActiveTrigger ](https://user-images.githubusercontent.com/98040092/212715996-b7ff79a1-81b0-432e-8f1c-8e4c5489b849.jpg)

fix:
if (this!== null) {
if (
typeof this._activeTrigger != 'undefined' &&
typeof this._activeTrigger.hover == 'undefined'
) {
this._activeTrigger.hover = false;
}
}

**Comment by GeoSot** [comment]
> fix:
if (this!== null) {
if (
typeof this._activeTrigger != 'undefined' &&
typeof this._activeTrigger.hover == 'undefined'
) {
this._activeTrigger.hover = false;
}
}


sorry to disappoint you, but this is not a fix, it is just a super defensive approach to save the situation of something really wrong (Tooltip is not initialized at all)

I am here to help, but I will need your cooperation, in order to replicate the issue. I have tried to many times this example, without results. 

Please, create a codepen example to be able to follow your code, and try to explain me in simple bullets (steps) how to replicate.

**Comment by njmkramer** [comment]
Thanxs for your reply, I wil updated the live test in the coming days

**Comment by njmkramer** [comment]
Explaination:

1: from top to bottom:
   focus each input -> it will turn red and have a hover 'enter a value'

2: from top to bottom:
   focus and type a value -> hover will disappear or the error will occur

3: from top to bottom:
clear the input 

4: repeat 1, 2 and 3 until the error comes up and it will

Sometimes the error came up very quickly, other times I had to repeat the 4 steps serveral times, as fast as I could, to trigger the error to come up.

I hope this helps you to see the problem

**Comment by GeoSot** [comment]
can you  please do it in a code pen in order to be able to see your code ? ( or provide an open project url for stackblitz)

**Comment by njmkramer** [comment]
url to the code:

https://stackblitz.com/edit/js-cq37dw?file=index.js

**Comment by njmkramer** [comment]
https://user-images.githubusercontent.com/98040092/214544689-ebedb56b-237f-4cb2-8e3a-23e8c0ad468a.mp4

screenshot of error occuring

**Comment by njmkramer** [comment]
@GeoSot see screenshot where the error occurs. Best regards Norbert

**Comment by hakenr** [comment]
I'm experiencing the very same issue when using Bootstrap with Blazor and trying to navigate to another route (removes the elements from DOM) when the tooltip is still displayed:
![2023-02-01_17-48-23](https://user-images.githubusercontent.com/12828888/216108263-3648228d-60dc-4288-936c-bf5dd0a2801b.gif)

The Blazor code is as simple as follows:
```razor
@inject NavigationManager NavigationManager

<HxButton Text="Navigate home"
	Tooltip="Navigate"
	Color="ThemeColor.Primary"
	OnClick="@(() => NavigationManager.NavigateTo(""))" />
```

`HxButton` is a component from a Blazor library wrapping Bootstrap: https://havit.blazor.eu/

For now, I'm not trying to give you a regular repro, just adding some additional info to the issue.

BTW: My original intention was to reproduce this issue (https://github.com/havit/Havit.Blazor/issues/457): 
![image](https://user-images.githubusercontent.com/12828888/216109090-a23d4424-9fdd-4ea0-a231-505c698932bf.png)
...but when I recreated the original scenario, the `_activeTrigger` error appeared instead.

**Comment by Andream98** [comment]
I am also experiencing this issue in `Bootstrap@5.2.3` even though my setup is a bit different than the one described by @njmkramer 

I am using the Tooltips class in a `Vue@2.7.14` custom directive that automatically instantiates tooltips on elements with the directive.

It is also really difficult to replicate the error in my case but from the experimenting I've done, at the time of error `this` is completely empty:
```
{
    "_element": null,
    "_config": null,
    "_isEnabled": null,
    "_timeout": null,
    "_isHovered": false,
    "_activeTrigger": null,
    "_popper": null,
    "_templateFactory": null,
    "_newContent": null,
    "tip": null,
    "_hideModalHandler": null
}
```

So this makes me think that in some way (that I still haven't managed to figure out): 
1. the element which is causing the error has its Tooltip instance disposed of via the `dispose()` function (hence all the `null` properties)

  <img width="784" alt="Screenshot 2023-02-28 at 13 37 54" src="https://user-images.githubusercontent.com/52160332/221856284-a09ad9c4-e934-43bb-a21b-a9bb697cf7b4.png">

  _from bootstrap.bundle.js:809_

2. but the element still has the `mouseover` Events attached to it even after the instance is disposed of (at least the `mouseleave`, which triggers the `hide()` function that causes `_isHovered` to be `false` unlike all the other properties that are `null`)

So I'm guessing the problem resides either in the Events management after the Tooltip instance is disposed of, or when it's re-instantiated on the same element after the previous instance was disposed of.

**Comment by alchimik** [comment]
simple live demo: https://codepen.io/alchimik-irk/pen/abapgLZ

**Comment by GeoSot** [comment]
> simple live demo: https://codepen.io/alchimik-irk/pen/abapgLZ

My friend, this is a wrong approach, as you are trying to dispose the tooltip instantly, not giving the proper time for `hide` process to get finished

the right approach on this is 
```js
setTimeout( () =>{  
  tooltipEl.addEventListener('hidden.bs.tooltip', ()=> { tooltipBs.dispose() } )
  tooltipBs.hide(); 
}, 2000);

```

ref: #38018

**Comment by Andream98** [comment]
That might be a wrong usage of the class but it is useful to reproduce the error consistently.

In my case I'm using the `dispose()` method (as the documentation states [here](https://getbootstrap.com/docs/5.3/components/tooltips/#methods)) to hide the tooltip and remove the instance from an item, but this is sometimes generating the error.

Here's my code:
<img width="555" alt="Screenshot 2023-03-01 at 12 44 58" src="https://user-images.githubusercontent.com/52160332/222130271-38fe8d59-0d0c-40c0-93d5-a986f2fcc0c8.png">

I'm guessing that when the `dispose()` method is called, another call to `hide()` gets executed at the same time maybe by the `mouseleave` event.

I think a failsafe in the `dispose()` method is required to prevent these edge cases.

**Comment by njmkramer** [comment]
sreencast of error occuring during disposing and mouseover/mouseleave.

https://user-images.githubusercontent.com/98040092/224481302-e55a3e92-e4de-4327-9673-3bc148f380d7.mp4

**Comment by alchimik** [comment]
#36080 - same problem, with a solution, not merged

**Comment by mahui-cn** [comment]
I ran into the same issue, it occur when I call tooltip.dispose() in unmount of component in React, while I change it to call tooltip.hide(), it is ok and also meet my demand.

**Comment by njmkramer** [comment]
@GeoSot  Hi, when can i or we, expect a solution for this issue. 
The uncaught error is a real pain in the a**.
Users have to reload the page because of this.
Thanxs in advance

**Comment by njmkramer** [comment]
I managed to find a workaround;
```
var popover = Popover.getInstance(obj);
if (popover !== null && typeof popover.dispose === 'function') {
  popover.disable();
  popover.hide();
  setTimeout(function () {
    popover.dispose();
  }, 300);
}
```

**Comment by TomONeill** [comment]
I ran into this error and because of the comments in this issue I was able to resolve it.

In my scenario I wanted to change the title/position after the tooltip was initialised.
I did this by disposing the tooltip and immediately re-initialising the tooltip with the latest values.
This works, however when the tooltip was shown and the title/position updated, it resulted in this error.

I found that you can use lambdas instead to always get the latest values, like so:
```ts
 new Tooltip(this.element, {
  "title": () => this.title,
  "placement": () => this.placement
});
```

Now I only dispose the tooltip when the element gets destroyed.

**Comment by tagliala** [comment]
I'm also having this issue, but it is quite random and I cannot provide a reproducible test case.

It is indeed related to `dispose()`, and the use case is a tooltip initialized with a [stimulus](https://stimulus.hotwired.dev/) controller

```js
  connect () {
    this.tooltip = new Tooltip(this.element)
  }

  disconnect () {
    this.tooltip.dispose()
  }
```

```
tooltip.js:534 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Tooltip._isWithActiveTrigger (tooltip.js:534:1)
    at complete (tooltip.js:268:1)
    at execute (index.js:226:1)
    at HTMLDivElement.handler (index.js:247:1)
    at triggerTransitionEnd (index.js:71:1)
    at index.js:253:1
```

**Comment by ArgoZhang** [comment]
same issue

**Comment by yads** [comment]
I'm running into this issue via with a wrapped popover in an Ember component. This is the basic component code.

```
class MyComponent extends Component {
  configurePopover(element) {
    this.popover = new bootstrap.Popover(element);
  }

  willDestroy() {
    this.popover.dispose();
  }

  someHandler() {
    this.popover.hide();
    doStuff();
  }
}
```

What's happening is in `someHandler` we hide the popover, however, sometimes `doStuff` causes the component to be removed from the DOM and destroyed, which causes `dispose` to be called. Then the error is thrown, because now in the hide complete handler the popover has been disposed.

What I've had to do is to run hide in a setTimeout.

```
  someHandler() {
    setTimeout(() => this.popover.hide(), 1);
    doStuff();
  }
```

This way if the popover is disposed, the hide call won't do anything. It does feel like the hide `complete` handler should check if the component has been disposed and stop execution early.

**Comment by francogiacobbi** [comment]
I'm having same troubles with this environment:

ASP.NET 4.6.2 - Bootstrap 5.3.3 - Jquery 3.7.1 - Bootstrap-Table 1.23.2

Problem is when i try to edit cell and update value (inside table and on database).

For  cell EDITING using bootstrap-editable.js with skycyclone-x-editable

I use popup editing text-box.

All is ok until application stores value in database.
Values are correctly stored in database.

Event onEditableHidden is perfect and popup text disapperead well.
New Value appears in table.

A thing that i can't understand is that tooltip.js (inside browser inspector) is located in
localhost:44300/lib/bootstrap/js/src/tooltip.js
but in my folder bootstrap there's not a js folder with src subfolder but in browser i can see code of tooltip.js
 
Bootstrap and Jquery Libraries are managed by Libman. 

In browser inspector i receive this error

If anyone has a workaround.....

Uncaught TypeError: can't convert null to object
    _isWithActiveTrigger tooltip.js:536
    hide tooltip.js:270
    g index.js:226
    a index.js:247
    s index.js:71
    _ index.js:253
    setTimeout handler*_ index.js:251
    _queueCallback base-component.js:49
    hide tooltip.js:282
    jQueryInterface popover.js:86
    jQuery 2
    jQueryInterface popover.js:75
    call bootstrap-editable.js:4834
    innerHide bootstrap-editable.js:4813
    hide bootstrap-editable.js:1149
    destroy bootstrap-editable.js:1256
    init bootstrap-editable.js:936
    i jQuery
    remove bootstrap-editable.js:1408
    jQuery 6
    value bootstrap-table.min.js:10
    value bootstrap-table-editable.min.js:10
    value bootstrap-table-filter-control.min.js:10
    value bootstrap-table-editable.min.js:10
    jQuery 4
    save bootstrap-editable.js:1221
    jQuery 5
    submit bootstrap-editable.js:286
    jQuery 3
    submit bootstrap-editable.js:243
    jQuery 10
    render bootstrap-editable.js:114
    jQuery 9
    render bootstrap-editable.js:92
    editableform bootstrap-editable.js:410
    jQuery 2
    editableform bootstrap-editable.js:401
    renderForm bootstrap-editable.js:1081
    show bootstrap-editable.js:1127
    show bootstrap-editable.js:1810
    toggle bootstrap-editable.js:1832
    init bootstrap-editable.js:1555
    jQuery 9
    init bootstrap-editable.js:1540
    Editable bootstrap-editable.js:1485
    editable bootstrap-editable.js:2147
    jQuery 2
    editable bootstrap-editable.js:2133
    value bootstrap-table-editable.min.js:10
    jQuery 2
    value bootstrap-table-editable.min.js:10
    each jQuery
    value bootstrap-table-editable.min.js:10
    value bootstrap-table-filter-control.min.js:10
    value bootstrap-table.min.js:10
    value bootstrap-table.min.js:10
    value bootstrap-table-filter-control.min.js:10
    timeoutId bootstrap-table-filter-control.min.js:10
    setTimeout handler*ag/< bootstrap-table-filter-control.min.js:10
    jQuery 6
        dispatch
        handle
        trigger
        trigger
        each
        each
[tooltip.js:536:18](https://localhost:44300/lib/bootstrap/js/src/tooltip.js)

**Comment by anitschke** [comment]
I am running into this issue when trying to use `Tooltip` inside of a [Lit](https://lit.dev/) custom element that wraps `Tooltip`. Something like this:

```js
import { LitElement } from "lit";
import { Tooltip as BootstrapTooltip } from "bootstrap";

class Tooltip extends LitElement {
  static properties = {
    content: { type: String },
  };

  render() {
    return html`<slot></slot>`;
  }

  connectedCallback() {
    super.connectedCallback();
    this._initializeTooltip();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this._tooltip) {
      this._tooltip.dispose();
    }
  }

  async _initializeTooltip() {
    await this.updateComplete;
    const slot = this.shadowRoot.querySelector("slot");
    const nodes = slot.assignedNodes({ flatten: true });
    const triggerElement = nodes.find(
      (node) => node.nodeType === Node.ELEMENT_NODE
    );

    this._tooltip = new BootstrapTooltip(triggerElement, {
      title: this.content,
      container: document.body,
    });
  }
}

customElements.define('my-tooltip', Tooltip);
```

It is used like this to give a tooltip to a specific element `<my-tooltip content="This is some tooltip text"><div>this element has a tooltip</div></my-tooltip>`

`connectedCallback` is called when the custom element is added to the DOM in order to initialize the tooltip. When the `my-tooltip` custom element is removed from the DOM `disconnectedCallback` is called to dispose of the tooltip since we shouldn't need it anymore.

Normally this all works fine. However I have recently had some automated tests sporadically fail with this same `Uncaught TypeError: Cannot convert undefined or null to object` error. In these tests I am clicking on a button that happens to be wrapped in a `<my-tooltip>` element. If the test runs fast enough then the tooltip starts to show up as part of hovering over the button to perform the click. Before the show transition can complete the test finishes, the custom element is removed from the DOM, resulting in `dispose()` being called. At some point when the next test is running the transition callback runs, but it errors out because we have already disposed of the tooltip and nulled out the `_activeTrigger` property.

I have been able to work around this for now by doing some hacky modification of the `<my-tooltip>` custom element class prototype within this test. However it feels like the real fix is that the Bootstrap `Tooltip` should be safe to calling `dispose` at any point in time, even during transitions.

As @Andream98 and others have mentioned the documentation states that `dispose()` method *"Hides and destroys an element’s tooltip ..."*. So it seems to me that it should be safe to call in my case where I wish to hide and destroy the tooltip because my custom element is being removed from the DOM.

There is also a big warning in the documentation:

> All API methods are asynchronous and start a transition. They return to the caller as soon as the transition is started, but before it ends. In addition, a method call on a transitioning component will be ignored.

If I read this extremely literally I interpret this to mean that the `dispose()` should be ignored in cases where the component is transitioning. Like I outlined above I think what is happening in my case is the call to `dispose()` is happening during the transition where we show the tooltip. Thus according to the doc it seems that call to `dispose()` should be ignored entirely. But if that is the case it seems like you can never safely call `dispose()` since there is always the chance that a user could be hovering over that element right before the call to `dispose()`? Or does this not about starting transitions only apply to the API and not actions taken by users?

**Comment by robbytx** [comment]
I agree with @Andream98:
> I'm guessing that when the dispose() method is called, another call to hide() gets executed at the same time maybe by the mouseleave event.
> I think a failsafe in the dispose() method is required to prevent these edge cases.

And @yads:
> What's happening is in someHandler we hide the popover, however, sometimes doStuff causes the component to be removed from the DOM and destroyed, which causes dispose to be called. Then the error is thrown, because now in the hide complete handler the popover has been disposed.

As they've both described, the problem is that oftentimes there is some event listener that triggers the tooltip/popover's `hide` method, and then there is some other independent code that is reacting to the same or subsequent event that wants to trigger the tooltip/popover's `dispose` method.  In many cases, this other code is reacting to the overarching React/Ember/whatever framework's instruction that the trigger element is being removed *immediately* from the DOM, such that delaying the `dispose` call is not really an option. 

I've created a simple CodePen repro using the Popover component with [Dismiss on next click](https://getbootstrap.com/docs/5.3/components/popovers/#dismiss-on-next-click) (i.e. `trigger=focus`) behavior, and a second button that simply calls `popover.dispose()`:  https://codepen.io/robbytx/pen/raBBqXQ

In this repro, there is no call to `popover.hide()` in sight -- it's triggered internally by the Popover's own `focusout` event listener.  The Dispose button here is a proxy for any UI element that could cause a web application to remove the trigger element from the DOM, and the only workaround to avoid this error is hook every such UI element and delay reacting for the duration of the popover's hide delay, which is unfeasible in all but the simplest web apps and would create noticeable delays in web app responsiveness.

IMHO there should be some solution here that permits `.dispose()` to be called after `.hide()` but before the hide transition has completed, without throwing an error.  (For similar reasons, I think it should also be permitted to call `.dispose()` after `.show()` but before the show transition has completed.)

In fact, this issue is a regression from Bootstrap 4.x, where calling `.dispose()` after `.hide()` did NOT throw an error.  See this same CodePen adapted to Bootstrap 4: https://codepen.io/robbytx/pen/azooQyo

**Comment by robbytx** [comment]
Sorry to post yet another comment but:

In fact, the above workaround is incomplete because the `hide` method's `complete` callback also expects `this._element` to be non-null.  Therefore the full workaround requires to monkey-patch the `_element` property with a DOMElement as well:
```js
popover.dispose();
// workaround for https://github.com/twbs/bootstrap/issues/37474
popover._activeTrigger = {};
popover._element = document.createElement('noscript'); // placeholder with no behavior
```

**Comment by karendolan** [comment]
Hi All, I'm seeing this issue in Bootstrap 5.3.7. 
I see an old pull https://github.com/twbs/bootstrap/pull/40856/files 

Meanwhile, do I need to both:
1. Add a hide() before dispose()
2. Add the extra 2 commands after dispose?
popover.dispose();
// workaround for https://github.com/twbs/bootstrap/issues/37474
popover._activeTrigger = {};
popover._element = document.createElement('noscript'); // placeholder with no behavior

**Comment by robbytx** [comment]
@karendolan IIRC calling `hide()` is not necessary.  The problem occurs when `hide()` has been called shortly before `dispose()` is called and/or the element is removed from the DOM, because `hide` waits for the CSS transition duration to elapse before completing its work.

Those two extra lines to re-initialize the `_activeTrigger` and `_element` attributes are necessary after calling `dispose()`, in order to avoid a Javascript error in the delayed work of the `hide` function.

**Comment by mdo** [comment]
v6-dev always initializes the tooltip's active-trigger state, so `_isWithActiveTrigger` can no longer hit the undefined value it was choking on. Closing — please open a new issue if the error resurfaces in v6-dev.

**Comment by MizouziE** [comment]
@mdo I agree that v6 will fix this, however a lot of us are still relying on v5.

 This is still reproducible on main at 6177d5f84. `js/src/base-component.js` is unchanged since the v5.3.8 release, `Tooltip._isWithActiveTrigger()` is unchanged, and `executeAfterTransition` still returns no cancel handle. Therefore I don't think anything landed for this, so would you consider reopening?

 The root cause is not `_isWithActiveTrigger()` itself. `dispose()` nulls every property on the instance but cannot cancel a callback already queued on a transition: `_queueCallback` -> `executeAfterTransition` registers a transitionend listener plus a `setTimeout` fallback calling `triggerTransitionEnd`, and neither is cancellable. That's why the reported stack trace comes through `triggerTransitionEnd`. `Tooltip.dispose()` clears `this._timeout`, which does not cover this, and `_disposePopper()` detaching the tip does not prevent the fallback from firing.

 This also explains why it was hard to reproduce it interactively as no mouse simulation is needed, since `show()` adds `.show` synchronously:

```js
const tooltip = new bootstrap.Tooltip(element)   // animation: true by default
tooltip.show()
tooltip.hide()      // queues complete() on the ~150ms fade
tooltip.dispose()   // nulls every property, cancels nothing
// ~155ms later: TypeError at tooltip.js:536
```

 @GeoSot already agreed that null-guarding `_isWithActiveTrigger()` is only defensive papering-over as it just moves the crash two lines down to `this._element.removeAttribute('aria-describedby')`. The queued callback has to not run at all.

 Worth noting **this isn't tooltip-specific**. Every component routes transition completion through `BaseComponent._queueCallback`, and Collapse, Toast, Modal, Alert, Tab, Offcanvas and Carousel all dereference `this._element` as the first statement of their completion callbacks. A guard in that one method fixes all of them. I have a patch with tests and will open a PR.

**Comment by mdo** [comment]
Thanks for doing that! I've tagged it for v5.4.0. My plan is to ship a v5 update along v6 stable, but possibly sooner.
